# Adapted from https://github.com/thijor/dp-cvep-speller (Thielen et al., 2021)
# Modified for the present thesis (conditions: classic/grating, contrast manipulation, 32-class layout)

[speller]
images_dir = "./cvep_speller/images/"
codes_dir = "./cvep_speller/codes/"
presentation_rate_hz = 60
quit_phrase = "!!"
key_space = "space"
key_clear = "<<"
key_backspace = "<-"

[[speller.banks]]
condition = "classic"
colors = ["black", "white", "green", "blue"]
contrasts = [10, 20, 30, 40, 60, 100]

[[speller.banks]]
condition = "grating"
colors = ["gray", "grating", "green", "blue"]
contrasts = [10, 20, 30, 40, 60, 100]

[speller.screen]
id = 1
resolution = [2560, 1440]
width_cm = 60.1
distance_cm = 60.0
background_color = [ 0, 0, 0,]
refresh_rate_hz = 120
full_screen = true

[speller.timing]
cue_s = 0.8
trial_s = 4.2
feedback_s = 0.7

[speller.keys]
shift_enabled = false
# according to Wei et al(2016), 3.8 degree key size with 1.0 degree spacing is the best
width_dva = 3.8
height_dva = 3.8
space_dva = 1.0
colors = [ "black", "white", "green", "blue",]
keys_upper = [
    ["A","B","C","D","E","F","G","H"],
    ["I","J","K","L","M","N","O","P"],
    ["Q","R","S","T","U","V","W","X"],
    ["Y","Z","dot","comma","question","exclam","space","backspace"]
]

[speller.text_fields]
height_dva = 2.3
background_color = [ -0.05, -0.05, -0.05,]

[speller.controls]
continue = [ "c",]
quit = [ "q", "escape",]

[speller.markers]
cue_start = "start_cue"
cue_stop = "stop_cue"
trial_start = "start_trial"
trial_stop = "stop_trial"
feedback_start = "start_feedback"
feedback_stop = "stop_feedback"
iti_start = "start_iti"
iti_stop = "stop_iti"
rest_start = "start_rest"
rest_stop = "stop_rest"

[decoder]
decoder_subset_layout_file = ""

[streams]
marker_stream_name = "marker-stream"
decoder_stream_name = "cvep-decoder-stream"

[training]
codes_file = "mseq_32_shift.npz"
block_size = 48
